name: e_library
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.0.3
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  open_file: ^3.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.0.3
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: MaisonNeue
      fonts:
        - asset: assets/fonts/Maison_Neue_Bold.ttf
        - asset: assets/fonts/Maison_Neue_Book.ttf
        - asset: assets/fonts/Maison_Neue_Light.ttf
        - asset: assets/fonts/Maison_Neue_Mono.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
